pipelines:

  - name: S_WF_022
    steps:
  
      - name: S_WF_022_001
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
  
      - name: S_WF_022_002
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_022_001
        execution:
          onExecute:
            - echo "Step 2 is running"
            - exit 1;
  
      - name: S_WF_022_003
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_022_002
        execution:
          onExecute:
            - echo "I should not be running"
