
pipelines:

  - name: S_WF_025
    configuration:
      nodePool: win_2019
    steps:

      - name: S_WF_025_001
        type: PowerShell
        execution:
          onExecute:
            - Write-Output "Step 1 is running"

      - name: S_WF_025_002
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_025_001
        execution:
          onStart:
            - add_run_variables step_2_var="foo"
          onExecute:
            - Write-Output "Step 2 is running"

      - name: S_WF_025_003
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_025_001
        execution:
          onStart:
            - add_run_variables step_3_var="bar"
          onExecute:
            - Write-Output "Step 3 is running"

      - name: S_WF_025_004
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_025_002
            - name: S_WF_025_003
        execution:
          onExecute:
            - Write-Output "step_2_var - ${step_2_var}"
            - Write-Output "step_3_var - ${step_3_var}"
            - if ("$step_2_var" -ne "foo") { throw "variable does not match expected value" }
            - if ("$step_3_var" -ne "bar") { throw "variable does not match expected value" }
