pipelines:
  - name: S_WF_001
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: S_WF_001_1
        type: Bash
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "step_1"
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"      
      - name: S_WF_001_2
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_001_1
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "step_2"
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
