resources:
  - name: S_WF_010_resource1
    type: PropertyBag
    configuration:
      runNumber: 0
  - name: S_WF_010_resource2
    type: PropertyBag
    configuration:
      runNumber: 0

pipelines:
  - name: pipeline_S_WF_010
    steps:
      - name: S_WF_010_trigger
        type: Bash
        execution:
          onExecute:
            - echo "test"
      - name: S_WF_010_input1
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_010_trigger
          outputResources:
            - name: S_WF_010_resource1
        execution:
          onExecute:
            - write_output S_WF_010_resource1 runNumber=${run_number}
      - name: S_WF_010_input2
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_010_trigger
          outputResources:
            - name: S_WF_010_resource2
        execution:
          onExecute:
            - echo "test"
      - name: S_WF_010
        type: Bash
        configuration:
          inputResources:
            - name: S_WF_010_resource1
              newVersionOnly: true
            - name: S_WF_010_resource2
              newVersionOnly: true
        execution:
          onExecute:
            - echo "test"
