resources:
  - name: S_WF_013_resource
    type: PropertyBag
    configuration:
      runNumber: 0

pipelines:
  - name: pipeline_S_WF_013_001
    steps:
      - name: S_WF_013_001
        type: Bash
        configuration:
          outputResources:
            - name: S_WF_013_resource
        execution:
          onExecute:
            - write_output S_WF_013_resource runNumber=${run_number}
  - name: pipeline_S_WF_013_002
    configuration:
      dependencyMode:
        waitOnParentComplete: true
    steps:
      - name: S_WF_013_002
        type: Bash
        configuration:
          inputResources:
            - name: S_WF_013_resource
              newVersionOnly: true
        execution:
          onExecute:
            - echo "test"
