
pipelines:

  - name: S_WF_016
    steps:

      - name: S_WF_016_001
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"

      - name: S_WF_016_002
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_016_001
        execution:
          onStart:
            - add_run_variables step_2_var="foo"
          onExecute:
            - echo "Step 2 is running"

      - name: S_WF_016_003
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_016_001
        execution:
          onStart:
            - add_run_variables step_3_var="bar"
          onExecute:
            - echo "Step 3 is running"

      - name: S_WF_016_004
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_016_002
            - name: S_WF_016_003
        execution:
          onExecute:
            - echo "step_2_var - ${step_2_var}"
            - echo "step_3_var - ${step_3_var}"
            - if [ "$step_2_var" != "foo" ]; then exit 1; fi
            - if [ "$step_3_var" != "bar" ]; then exit 1; fi
