pipelines:
     
  - name: S_WF_020
    steps:
  
      - name: S_WF_020_001
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
  
      - name: S_WF_020_002
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_020_001
          affinityGroup: some_ag
        execution:
          onExecute:
            - exit 1;
  
      - name: S_WF_020_003
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_020_002
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "I should not be running."
  
      - name: S_WF_020_004
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_020_003
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "I should not be running too."
